---
- name: update os
  yum:
    name: '*'
    state: latest
  become: true
- name: install some package 
  yum: 
    name: "{{ item }}"
    state: present
  loop: 
    - epel-release
    - python3
    - python3-pip
    - git
    - device-mapper-persistent-data
    - lvm2

- name: add docker repo
  yum_repository:
    name: docker 
    baseurl:  https://download.docker.com/linux/centos/7/x86_64/stable/
    enbaled: yes 
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: add docker-ce repos 
  get_url: 
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
- name: update package 
  update_cache: yes 

- name: install docker 
  yum: 
    name: "{{ item }}"
    state: present
  loop: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io 
    - docker-buildx-plugin 
    - docker-compose-plugin
- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true 
  notify: restart docker service