---
# tasks file for role-webapp
- include_tasks: "docker-centos.yaml"
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
- include_tasks: "docker-ubuntu.yaml"
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- include_tasks: "apache-container.yaml"